### ISSUE TITLE
do this work?

### ISSUE THREAD

**Issue by dries-c** [lolcraftboy14/bigbrother-14.2-end-1.9.2#1]

**Comment by lolcraftboy14** [comment]
Yes it work

**Comment by dries-c** [comment]
real?

**Comment by dries-c** [comment]
i can not connect with pc!

**Comment by lolcraftboy14** [comment]
@Driesboy  oke

**Comment by thelucyclub** [comment]
Console:

> Warning: file_get_contents(C:\Users********_\Desktop\MC-Servers\PE\Factions 0.15\plugins\BigBrother/steve.yml): failed to open stream: No such file or directory in C:\Users\**_******\Desktop\MC-Servers\PE\Factions 0.15\plugins\bigbrother-14.2-end-1.9.2-master\src\shoghicp\BigBrother\DesktopPlayer.php on line 218
> [08:37:08] [Server thread/CRITICAL]: [Network] Stopped interface shoghicp\BigBrother\network\ProtocolInterface due to Undefined class constant 'REMOVE_PLAYER_PACKET'
> [08:37:08] [Server thread/EMERGENCY]: [ServerThread #6500] ServerThread crashed!
